---

- set_fact:
    kubernetes_ip_address: "{{ item }}"
  when: "item | ipaddr( kubernetes_subnet )"
  with_items: "{{ ansible_all_ipv4_addresses | difference([kubernetes_vip_ip]) }}"

- name: Clean /etc/hosts
  ansible.builtin.lineinfile: 
    dest: /etc/hosts 
    regexp: '^127.0(.*){{ item }}' 
    state: absent
  loop: "{{ ansible_play_batch }}"

- name: Generate /etc/hosts
  ansible.builtin.lineinfile: 
    dest: /etc/hosts 
    regexp: '.*{{ item }}$' 
    line: "{{ hostvars[item].kubernetes_ip_address }} {{ item }}" 
    state: present
  when: hostvars[item].kubernetes_ip_address is defined
  loop: "{{ ansible_play_batch }}"